version: '3.8'

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./docker/nginx/development/default.conf:/etc/nginx/conf.d/default.conf:ro
            - static_volume:/final/backend/django_static
        depends_on:
          - backend 
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /final/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/final/backend/django_static
        expose:
            - 8000 
        depends_on:
            - db  
    redis:
        image: redis:alpine
        container_name: redis  
        ports:
            - 6379:6379
    db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=9008978
        container_name: postgres_db
         

volumes:
    static_volume: {}