import React, {useEffect} from 'react';
import { Button, Card, Container, Icon, Image, Segment, Loader, Dimmer, Message, Grid, Label, Item, Header, Form, Divider, Select, Tab } from 'semantic-ui-react'
import img from '../../image/up-arrow.png'
const TermsOfService = () => {
    useEffect(() => {
        handleClick()
    }, []);
    const handleClick = ()=>{
        window.scrollTo(0, 0)
    }
    return (
        <React.Fragment>
            <Container style={{ marginTop: '50px' }}>
                <Header textAlign='center' as='h1'>Terms of Service</Header>
                <p>1. PRIVACY</p>
                <p>Your privacy is very important to us at Future House. To better protect your rights we have provided the Future House.com Privacy Policy to explain our privacy practices in detail. Please review the Privacy Policy to understand how Future House collects and uses the information associated with your Account and/or your use of the Services (the “User Information”). By using the Services or providing information on the Site, you:
                    (i) consent to Future House's collection, use, disclosure and/or processing of your Content, personal data and User Information as described in the Privacy Policy;
                    (ii) agree and acknowledge that the proprietary rights of your User Information are jointly owned by you and Future House; and
                    (iii) shall not, whether directly or indirectly, disclose your User Information to any third party, or otherwise allow any third party to access or use your User Information, without Future House’s prior written consent.
                    Users in possession of another User’s personal data through the use of the Services (the “Receiving Party”) hereby agree that, they will (i) comply with all applicable personal data protection laws with respect to any such data; (ii) allow the User whose personal data the Receiving Party has collected (the “Disclosing Party”) to remove his or her data so collected from the Receiving Party’s database; and (iii) allow the Disclosing Party to review what information have been collected about them by the Receiving Party, in each case of (ii) and (iii) above, in compliance with and where required by applicable laws.</p>
                <p>2. LIMITED LICENSE</p>
                <p>Future House grants you a limited and revocable license to access and use the Services subject to the terms and conditions of these Terms of Service. All proprietary Content, trademarks, service marks, brand names, logos and other intellectual property (“Intellectual Property”) displayed in the Site are the property of Future House and where applicable, third party proprietors identified in the Site. No right or licence is granted directly or indirectly to any party accessing the Site to use or reproduce any Intellectual Property, and no party accessing the Site shall claim any right, title or interest therein. By using or accessing the Services you agree to comply with the copyright, trademark, service mark, and all other applicable laws that protect the Services, the Site and its Content. You agree not to copy, distribute, republish, transmit, publicly display, publicly perform, modify, adapt, rent, sell, or create derivative works of any portion of the Services, the Site or its Content. You also may not, without our prior written consent, mirror or frame any part or whole of the contents of this Site on any other server or as part of any other website. In addition, you agree that you will not use any robot, spider or any other automatic device or manual process to monitor or copy our Content, without our prior written consent (such consent is deemed given for standard search engine technology employed by Internet search websites to direct Internet users to this website).
                    You are welcome to link to the Site from your website, provided that your website does not imply any endorsement by or association with Future House. You acknowledge that Future House may, in its sole discretion and at any time, discontinue providing the Services, either in part or as a whole, without notice.</p>
                <p>3. SOFTWARE</p>
                <p>Any software provided by us to you as part of the Services is subject to the provisions of these Terms of Service. Future House reserves all rights to the software not expressly granted by Future House hereunder. Any third-party scripts or code, linked to or referenced from the Services, are licensed to you by the third parties that own such scripts or code, not by Future House.</p>
                <p>4. ACCOUNTS AND SECURITY</p>
                <p>Some functions of our Services require registration for an Account by selecting a unique user identification ("User ID") and password, and by providing certain personal information. If you select a User ID that Future House, in its sole discretion, finds offensive or inappropriate, Future House has the right to suspend or terminate your Account. You may be able to use your Account to gain access to other products, websites or services to which we have enabled access or with which we have tied up or collaborated. Future House has not reviewed, and assumes no responsibility for any third party content, functionality, security, services, privacy policies, or other practices of those products, websites or services. If you do so, the terms of service for those products, websites or services, including their respective privacy policies, if different from these Terms of Service and/or our Privacy Policy, may also apply to your use of those products, websites or services.
                    You agree to (a) keep your password confidential and use only your User ID and password when logging in, (b) ensure that you log out from your account at the end of each session on the Site, (c) immediately notify Future House of any unauthorised use of your Account, User ID and/or password, and (d) ensure that your Account information is accurate and up-to-date. You are fully responsible for all activities that occur under your User ID and Account even if such activities or uses were not committed by you. Future House will not be liable for any loss or damage arising from unauthorised use of your password or your failure to comply with this Section.
                    You agree that Future House may for any reason, in its sole discretion and with or without notice or liability to you or any third party, immediately terminate your Account and your User ID, remove or discard from the Site any Content associated with your Account and User ID, withdraw any subsidies offered to you, cancel any transactions associated with your Account and User ID, temporarily or in more serious cases permanently withhold any sale proceeds or refunds, and/or take any other actions that Future House deems necessary. Grounds for such actions may include, but are not limited to, actual or suspected (a) extended periods of inactivity, (b) violation of the letter or spirit of these Terms of Service, (c) illegal, fraudulent, harassing, defamatory, threatening or abusive behaviour (d) having multiple user accounts, (e) buying products on the Site for the purpose of commercial re-sale, (f) abnormal or excessive purchasing of products from the same Seller or related group of Sellers, (g) voucher abuse (including, but not limited to, selling of vouchers to third parties, selling of vouchers or other credits at a significant markup above face value, and/or abnormal or excessive use of vouchers on the Site), or (h) behaviour that is harmful to other Users, third parties, or the business interests of Future House. Use of an Account for illegal, fraudulent, harassing, defamatory, threatening or abusive purposes may be referred to law enforcement authorities without notice to you. If a legal dispute arises or law enforcement action is commenced relating to your Account or your use of the Services for any reason, Future House may terminate your Account immediately with or without notice.</p>
                <p>5. TERM OF USE</p>
                <p>The license for use of this Site and the Services is effective until terminated. This license will terminate as set forth under these Terms of Service or if you fail to comply with any term or condition of these Terms of Service. In any such event, Future House may effect such termination with or without notice to you.</p>
                <p>You understand that all Content, whether publicly posted or privately transmitted, is the sole responsibility of the person from whom such Content originated. This means that you, and not Future House, are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available through the Site. You understand that by using the Site, you may be exposed to Content that you may consider to be offensive, indecent or objectionable. To the maximum extent permitted by applicable law, under no circumstances will Future House be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of, or reliance on, any Content posted, emailed, transmitted or otherwise made available on the Site.</p>
            </Container>
            <div className='back-top-btn' onClick={handleClick}>
                <Image src={img} size='mini'/>
            </div>

        </React.Fragment>

    );
}

export default TermsOfService;
