from django.urls import path
from django.urls.conf import include
from rest_framework import routers
from rest_framework.routers import DefaultRouter
from .views import *
from django.views.decorators.csrf import csrf_exempt
from core.views import get_user_contact
urlpatterns =[
    path('super-user/', CheckAdminView.as_view()),
    path('is-staff/', CheckStaffView.as_view()),
    path('user-id/', UserIDView.as_view()),
    path('product/create/', CreateItemView.as_view()),
    path('product/<pk>/update/', ItemUpdateView.as_view(), name="update-product"),
    path('user/<pk>/update/', UserUpdateView.as_view(), name="update-user"),
    path('products/', ItemListView.as_view()),
    path('user-list/', UserListView.as_view()),
    path('user-profile-list/', UserProfileListView.as_view()),
    path('products/<pk>/', ItemDetailView.as_view(), name='product-detaill'),
    path('user/<pk>/', UserDetailView.as_view(), name="user-detail"),
    path('add-to-cart/', AddToCartView.as_view()),
    path('order-summary/', OrderDetailView.as_view()),
    path('checkout/', PaymentView.as_view()),
    path('payments/', PaymentListView.as_view()),
    path('order-user/<int:userID>/', OrderByIDView.as_view()),
    path('payment-user/<int:userID>/', PaymentByIDView.as_view()),
    path('add-coupon/', AddCouponView.as_view()),
    path('order-items/<pk>/delete/', OrderItemDeleteView.as_view()),
    path('search/<str:q>', ProductFilter.as_view()),
    path('download/<pk>/', DownloadView.as_view()),
    path('comment-reply/<int:Comment_ID>/', GetCommentReply.as_view()),
    path('comment/<int:Item_ID>/', GetComment.as_view()),
    path('post-comment/', ReceiveComment.as_view()),
    path('post-comment-reply/', ReceiveCommentReply.as_view()),
    path('post-list/', PostListView.as_view()),
    path('post/<pk>/', PostDetailView.as_view(), name="blog-detail"),
    path('file/<int:Item_ID>/create/', FileCreateView.as_view()),
    path('document/<int:Item_ID>/create/', DocumentCreateView.as_view()),
    path('image/<int:Item_ID>/create/', ImageCreateView.as_view()),
    path('file/<pk>/delete/', FileDeleteView.as_view()),
    path('document/<pk>/delete/', DocumentDeleteView.as_view()),
    path('images/<pk>/delete/', ImagesDeleteView.as_view()),
    path('product/<pk>/delete/', ItemDeleteView.as_view(), name="delete-product"),
    path('order-list/', OrderListView.as_view()),
    path('coupon-list/', CouponListView.as_view()),
    path('coupon-create/', CouponCreateView.as_view()),
    path('coupon-detail/<pk>/', CouponDetailView.as_view()),
    path('coupon/<pk>/update/', CouponUpdateView.as_view()),
    path('coupon/<pk>/delete/', CouponDeleteView.as_view()),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name="blog-delete"),
    path('post-create/', PostCreateView.as_view()),
    # path('ckeditor/upload/', csrf_exempt(ImageCKEditorUploadView.as_view()), name='post-create'), 
    path('post/<pk>/update/', PostUpdateView.as_view(), name="blog-update"),
    path('send-email/', SendEmailView.as_view()),
    path('send-email/confirm/', SendEmailConfirm.as_view()),
    path('products-list-inf/', ItemListInfiniteView.as_view()),
    path('order-list-inf/', OrderListInfiniteView.as_view()),
    path('analyze-payment/', AnalyzePayment.as_view()),
    path('analyze-order/', AnalyzeOrder.as_view()),
    path('analyze-user/', AnalyzeUser.as_view()),
    path('add-wish-list/<int:id>/', AddToWishlist.as_view()),
    path('wish-list/', Wishlist.as_view()),
    path('check-wish-list/<pk>/', CheckWishlistView.as_view()),
    path('rate-star/', RateStar.as_view()),
    path('products-top/', ItemTopListView.as_view()),
    path('blogs-list-inf/', BlogListInfiniteView.as_view()),
    path('payment-stripe/', StripePayment.as_view()),
    path('chat-list/', ChatListView.as_view()),
    path('chat/create/', ChatCreateView.as_view()),
    path('chat/<pk>', ChatDetailView.as_view()),
    path('chat/<pk>/update/', ChatUpdateView.as_view()),
    path('chat/<pk>/delete/', ChatDeleteView.as_view()),
    path('user-contact/<str:username>/', ContactUser.as_view()),
    path('sale-per-day/', SalePerDayView.as_view()),
    path('block-user/', BlockUserListView.as_view())

]