# Generated by Django 3.2 on 2021-05-20 09:59

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210511_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='baths',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='beds',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='garages',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='square_foot',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='stories',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', 'Bungalow'), ('2', 'Classical'), ('3', 'Modern'), ('4', 'Traditional'), ('5', 'Luxury')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('T', 'Trending')], max_length=1),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.get_img_filename, verbose_name='Image')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
