# Generated by Django 3.2 on 2021-05-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210520_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='core.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='baths',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='beds',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='garages',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='square_foot',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='stories',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
