# Generated by Django 3.2 on 2021-05-26 09:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210520_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file_mtl',
            field=models.FileField(default=False, upload_to=core.models.select_id),
        ),
        migrations.AlterField(
            model_name='item',
            name='file_obj',
            field=models.FileField(default=False, upload_to=core.models.select_id),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('item', 'image')},
        ),
    ]
