# Generated by Django 3.2 on 2021-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210612_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
