# Generated by Django 3.2 on 2021-07-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_paymentitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.payment'),
        ),
    ]
