# Generated by Django 3.2 on 2021-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_paymentitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentitem',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(to='core.PaymentItem'),
        ),
    ]
