# Generated by Django 3.2 on 2021-07-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210703_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='itemIDsold',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='listURL',
        ),
    ]
