# Generated by Django 3.2 on 2021-07-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_userextend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isStaff',
        ),
    ]
