# Generated by Django 3.2 on 2021-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210708_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Classical', 'Classical'), ('Modern', 'Modern'), ('Traditional', 'Traditional'), ('Luxury', 'Luxury')], max_length=20),
        ),
    ]
