# Generated by Django 3.2 on 2021-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_files3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_mtl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='file_obj',
        ),
    ]
