# Generated by Django 3.2 on 2021-07-10 07:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210709_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=core.models.create_folder, verbose_name='Image'),
        ),
    ]
