# Generated by Django 3.2 on 2021-07-10 09:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files3d',
            name='file',
            field=models.FileField(default=False, upload_to=core.models.create_folder, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=core.models.get_img_filename, verbose_name='Image'),
        ),
    ]
