# Generated by Django 3.2 on 2021-07-11 07:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210710_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files3d',
            name='file',
            field=models.FileField(default=False, upload_to=core.models.create_folder),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=core.models.get_img_filename),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=core.models.create_folder),
        ),
    ]
