# Generated by Django 3.2 on 2021-07-12 08:51

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210712_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='ThumbnailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_img_filename, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='core.item')),
            ],
        ),
    ]
