# Generated by Django 3.2 on 2021-07-12 09:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210712_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.create_folder, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='ThumbnailItem',
        ),
    ]
