# Generated by Django 3.2 on 2021-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(blank=True, to='core.Message')),
                ('participants', models.ManyToManyField(blank=True, related_name='chats', to='core.Contact')),
            ],
        ),
    ]
