# Generated by Django 3.2 on 2021-10-31 10:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_filedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='document',
            field=models.FileField(default=False, upload_to=core.models.get_img_filename, verbose_name='File'),
        ),
    ]
