# Generated by Django 3.2 on 2021-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_filedocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
